### ISSUE TITLE
AuthenticatorLauncher does not start because of a NullPointerException

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#58]
<pre>
03:32:21.600 [main] ERROR o.o.j.p.Launcher ═╦═⚄ bco was started with restrictions!
03:32:21.600 [main] ERROR o.o.j.p.Launcher  ╚══╦═⚄ Errors during startup phase!
03:32:21.624 [main] ERROR o.o.j.p.Launcher     ╚══╦═⚀ Could not launch AuthenticatorLauncher!
03:32:21.624 [main] ERROR o.o.j.p.Launcher        ╚══╦═⚀ java.lang.NullPointerException
03:32:21.624 [main] ERROR o.o.j.p.Launcher           ╚════⚀ NullPointerException
03:32:21.624 [main] ERROR o.o.j.p.Launcher =====================================
03:32:21.641 [main] ERROR o.o.j.p.Launcher bco was started with restrictions!
org.openbase.jul.exception.MultiException: bco was started with restrictions!
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
        at org.openbase.jul.pattern.launch.AbstractLauncher.main(AbstractLauncher.java:367)
        at org.openbase.bco.manager.util.launch.BCOLauncher.main(BCOLauncher.java:52)
Caused by: org.openbase.jul.exception.MultiException: Errors during startup phase!
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
        at org.openbase.jul.pattern.launch.AbstractLauncher.main(AbstractLauncher.java:357)
        ... 1 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not launch AuthenticatorLauncher!
        at org.openbase.jul.pattern.launch.AbstractLauncher.main(AbstractLauncher.java:346)
        ... 1 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.openbase.jul.pattern.launch.AbstractLauncher.main(AbstractLauncher.java:333)
        ... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.openbase.bco.authentication.lib.CredentialStore.saveStore(CredentialStore.java:116)
        at org.openbase.bco.authentication.lib.CredentialStore.shutdown(CredentialStore.java:285)
        at org.openbase.bco.authentication.core.AuthenticatorController.deactivate(AuthenticatorController.java:182)
        at org.openbase.jul.iface.Manageable.shutdown(Manageable.java:38)
        at org.openbase.jul.pattern.launch.AbstractLauncher.launch(AbstractLauncher.java:194)
        at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:324)
        at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:320)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
03:32:21.643 [main] ERROR o.o.j.p.Launcher =====================================
</pre>

**Comment by DivineThreepwood** [comment]
The nullpointer seems to occur if the Authenticator was never initialized.

**Comment by DivineThreepwood** [comment]
Has been addressed and fixed in #68
