### ISSUE TITLE
Deadlock on BCO startup using authentication

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.authentication#60]
<pre>
Found one Java-level deadlock:
=============================
"pool-1-thread-15":
  waiting to lock monitor 0x00007f343c001c58 (object 0x00000006c7078e68, a org.openbase.bco.authentication.lib.SessionManager),
  which is held by "pool-1-thread-4"
"pool-1-thread-4":
  waiting to lock monitor 0x00007f33f800c868 (object 0x00000006c70f8270, a org.openbase.jul.schedule.SyncObject),
  which is held by "pool-1-thread-5"
"pool-1-thread-5":
  waiting to lock monitor 0x00007f343c001c58 (object 0x00000006c7078e68, a org.openbase.bco.authentication.lib.SessionManager),
  which is held by "pool-1-thread-4"

Java stack information for the threads listed above:
===================================================
"pool-1-thread-15":
	at org.openbase.bco.authentication.lib.SessionManager.login(SessionManager.java:182)
	- waiting to lock <0x00000006c7078e68> (a org.openbase.bco.authentication.lib.SessionManager)
	at org.openbase.bco.registry.login.SystemLogin.loginBCOUser(SystemLogin.java:62)
	at org.openbase.bco.manager.app.core.AppManagerController.activate(AppManagerController.java:78)
	at org.openbase.jul.pattern.launch.AbstractLauncher.launch(AbstractLauncher.java:182)
	- locked <0x00000006c7197508> (a org.openbase.jul.schedule.SyncObject)
	at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:324)
	at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:320)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"pool-1-thread-4":
	at org.openbase.bco.registry.lib.com.AbstractVirtualRegistryRemote.equalMessageCounts(AbstractVirtualRegistryRemote.java:161)
	- waiting to lock <0x00000006c70f8270> (a org.openbase.jul.schedule.SyncObject)
	at org.openbase.bco.registry.lib.com.AbstractVirtualRegistryRemote.isDataAvailable(AbstractVirtualRegistryRemote.java:146)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry.lambda$activate$0(SynchronizedRemoteRegistry.java:228)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry$$Lambda$10/232801518.update(Unknown Source)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:251)
	- locked <0x00000006c7078ef0> (a org.openbase.jul.pattern.AbstractObservable$3)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:190)
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:297)
	at org.openbase.bco.authentication.lib.SessionManager.login(SessionManager.java:183)
	- locked <0x00000006c7078e68> (a org.openbase.bco.authentication.lib.SessionManager)
	at org.openbase.bco.registry.login.SystemLogin.loginBCOUser(SystemLogin.java:62)
	at org.openbase.bco.manager.user.core.UserManagerController.activate(UserManagerController.java:84)
	at org.openbase.jul.pattern.launch.AbstractLauncher.launch(AbstractLauncher.java:182)
	- locked <0x00000006c71b8560> (a org.openbase.jul.schedule.SyncObject)
	at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:324)
	at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:320)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"pool-1-thread-5":
	at org.openbase.bco.authentication.lib.SessionManager.isAuthenticated(SessionManager.java:439)
	- waiting to lock <0x00000006c7078e68> (a org.openbase.bco.authentication.lib.SessionManager)
	at org.openbase.bco.authentication.lib.AuthorizationFilter.beforeFilter(AuthorizationFilter.java:104)
	at org.openbase.jul.pattern.AbstractFilter.filter(AbstractFilter.java:45)
	at org.openbase.bco.registry.lib.com.AbstractVirtualRegistryRemote.equalMessageCounts(AbstractVirtualRegistryRemote.java:165)
	- locked <0x00000006c70f8270> (a org.openbase.jul.schedule.SyncObject)
	at org.openbase.bco.registry.lib.com.AbstractVirtualRegistryRemote.isDataAvailable(AbstractVirtualRegistryRemote.java:146)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.waitForData(RSBRemoteService.java:1136)
	at org.openbase.bco.registry.lib.com.AbstractVirtualRegistryRemote.waitForData(AbstractVirtualRegistryRemote.java:129)
	at org.openbase.bco.registry.agent.remote.CachedAgentRegistryRemote.waitForData(CachedAgentRegistryRemote.java:110)
	at org.openbase.bco.registry.remote.Registries.waitForData(Registries.java:307)
	at org.openbase.bco.manager.agent.core.AgentManagerController.activate(AgentManagerController.java:82)
	at org.openbase.jul.pattern.launch.AbstractLauncher.launch(AbstractLauncher.java:182)
	- locked <0x00000006c71a4f80> (a org.openbase.jul.schedule.SyncObject)
	at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:324)
	at org.openbase.jul.pattern.launch.AbstractLauncher$1.call(AbstractLauncher.java:320)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</pre>

Short description:
Methods on the SessionManager are synchronized. One thread (pool-1-thread-4) starts a login process so the SessionManager is locked. Another thread (pool-1-thread-5) wants to check remote registries and therefore needs to use the isAuthenticated method from the SessionManager. The first thread (pool-1-thread-4) handles observer notifications because of the login which triggers another check for the remote registries which are already locked.

I think a simple solution would be to make the observer notification of the SessionManager parallel.

**Comment by pLeminoq** [comment]
Done in commit 90fc70979af35636d20e52045f6afa6c9e311702
