### ISSUE TITLE
SessionExpiredException thrown but no relogin performed

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#78]
This issue currently occurs after around  3 - 5 days uptime. 

* [ ] Clarify why the session expires because actually it should be auto extended.
* [ ] Why is no relogin performed when this exception occurs?

<pre>
19:42:23.251 [pool-1-thread-369630] ERROR o.o.b.r.a.c.ActivityRegistryController ═╦═⚀ Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
19:42:23.251 [pool-1-thread-369630] ERROR o.o.b.r.a.c.ActivityRegistryController  ╚════⚀ Request timestamp [13.2.2020 - 19:42:23:244] is not within ticket validity period [31.1.2020 - 21:11:36:55] - [7.2.2020 - 21:15:36:55]
19:42:23.251 [pool-1-thread-369630] ERROR o.o.b.r.a.c.ActivityRegistryController =====================================
19:42:23.255 [pool-1-thread-369630] ERROR o.o.b.r.a.c.ActivityRegistryController Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
        at org.openbase.jul.communication.controller.RPCHelper.lambda$registerMethod$1(RPCHelper.java:165)
        at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:121)
        at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:203)
        at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:174)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.openbase.jul.communication.controller.RPCHelper.lambda$registerMethod$1(RPCHelper.java:133)
        ... 7 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor744.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openbase.jul.communication.controller.RPCHelper.lambda$null$0(RPCHelper.java:130)
        ... 4 common frames omitted
Caused by: org.openbase.bco.authentication.lib.exception.SessionExpiredException: Request timestamp [13.2.2020 - 19:42:23:244] is not within ticket validity period [31.1.2020 - 21:11:36:55] - [7.2.2020 - 21:15:36:55]
        at org.openbase.bco.authentication.lib.AuthenticationServerHandler.validateTicket(AuthenticationServerHandler.java:220)
        at org.openbase.bco.authentication.lib.AuthenticatedServerManager.verifyClientServerTicket(AuthenticatedServerManager.java:147)
        at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedControllerServer.requestDataAuthenticated(AbstractAuthenticatedControllerServer.java:107)
        ... 8 common frames omitted
19:42:23.256 [pool-1-thread-369630] ERROR o.o.b.r.a.c.ActivityRegistryController =====================================
</pre>

**Comment by pLeminoq** [comment]
This does not solve the issue, but either the component with that ticket is running for a lot longer than 3 - 5 days or the authenticator is distributing outdated tickets. A validity period of [31.1.2020 - 21:11:36:55] - [7.2.2020 - 21:15:36:55] means that this ticket was generated on the 31st of January. So, in order for this to happen the component should have been running since then. Furthermore, the component has not performed any action since then (because every action should update the ticket) or, which is more likely to cause such a bug, somehow the session manager exchanged an up-to-date ticket for an outdated one.

**Comment by DivineThreepwood** [comment]
> So, in order for this to happen the component should have been running since then.

Yes, you are right, possibly openhab and therefore the bco-eclipse-smarthome binding was running since 31st of January. But BCO was restarted at least a couple of times since then.
> Furthermore, the component has not performed any action since then (because every action should update the ticket)

Is this actually possible in a live system? I mean any MotionSensor state update is triggering a `requestDataAuthenticated` that then updates the ticket, right?

>  somehow the session manager exchanged an up-to-date ticket for an outdated one.

But even then, we have two different bugs because no relogin is performed, right?

**Comment by pLeminoq** [comment]
Should be fixed by commit 08f7872af661fd8281d34f8b8151ce6e56cf9eb7. Most likely a remote instance remained running while BCO was restarted. Then an old ticket is used for the first requests. The problem was that the SessionManager did not timeout on some requests. Therefore, the re-login failed because of a deadlock.
