### ISSUE TITLE
loginUserAfterSystemLoginFailure Test fails

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#80]
Could you investigate what's going on here?
Checkout experimental branch in order to reproduce the issue.

<pre>
loginUserAfterSystemLoginFailure
09:18:41.976 [Thread-16] INFO  o.o.b.a.l.SessionManager Login failed:
org.openbase.jul.exception.CouldNotPerformException: Could not login
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:412)
	at org.openbase.bco.authentication.lib.SessionManager.loginClient(SessionManager.java:305)
	at org.openbase.bco.authentication.lib.SessionManager.loginClient(SessionManager.java:275)
	at org.openbase.bco.authentication.test.SessionManagerTest.loginUserAfterSystemLoginFailure(SessionManagerTest.java:162)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
Caused by: org.openbase.jul.exception.FatalImplementationErrorException: Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Decryption of [[B@ad61098] failed
	at org.openbase.bco.authentication.lib.EncryptionHelper.decrypt(EncryptionHelper.java:300)
	at org.openbase.bco.authentication.lib.EncryptionHelper.decrypt(EncryptionHelper.java:245)
	at org.openbase.bco.authentication.lib.AuthenticationClientHandler.handleKeyDistributionCenterResponse(AuthenticationClientHandler.java:62)
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:378)
	... 12 common frames omitted
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: Missing key encoding
	at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:251)
	at java.base/java.security.KeyFactory.generatePrivate(KeyFactory.java:390)
	at org.openbase.bco.authentication.lib.EncryptionHelper.decrypt(EncryptionHelper.java:287)
	... 15 common frames omitted
Caused by: java.security.InvalidKeyException: Missing key encoding
	at java.base/sun.security.rsa.RSAPrivateCrtKeyImpl.<init>(RSAPrivateCrtKeyImpl.java:127)
	at java.base/sun.security.rsa.RSAPrivateCrtKeyImpl.newKey(RSAPrivateCrtKeyImpl.java:80)
	at java.base/sun.security.rsa.RSAKeyFactory.generatePrivate(RSAKeyFactory.java:356)
	at java.base/sun.security.rsa.RSAKeyFactory.engineGeneratePrivate(RSAKeyFactory.java:247)
	... 17 common frames omitted
</pre>

**Comment by DivineThreepwood** [comment]
After looking into the test routine, this behaviour is intended because its validated by the test that an exception is thrown in case an invalid key is passed. However, there are two things kind of weird:
1. Why is the exception printed even when the logger is set to be quite?
2. Why is an FatalImplementation error thrown in this case?

**Comment by DivineThreepwood** [comment]
1. was caused by 2. since FatalImplementationErrors are always printed even when the logger is set to quied. After fixing the exception handling in case the keys are missing no further misleading logs are printed. Issue fixed by: openbase/jul#808337db
