### ISSUE TITLE
Error "Data must not be longer than 117 bytes" when starting bco device manager bundle

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#81]
I have implemented a way to start the main bco binary with different device manager. Those can now easily be declared via command line argument e.g. `--device-manager openhab` This is perfect for the pi where both components share the same registry and unit remote cache when started within one binary in order to save system resources.
However, some authentication components behave strange when starting the bco base launcher and the openhab device manager launcher within a single binary. Any Idea?

How to reproduce: 
* start spread
* provide a local bco db
* execute: `bco --device-manager openhab --openhab-config /tmp --sitemap /tmp`

<pre>
20:40:06.143 [pool-1-thread-46] ERROR o.o.b.a.l.EncryptionHelper ═╦═⚀ Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Unable to encrypt object[[B@8c9d9a1]
20:40:06.143 [pool-1-thread-46] ERROR o.o.b.a.l.EncryptionHelper  ╚════⚀ Data must not be longer than 117 bytes
20:40:06.143 [pool-1-thread-46] ERROR o.o.b.a.l.EncryptionHelper =====================================
20:40:06.159 [pool-1-thread-46] ERROR o.o.b.a.l.EncryptionHelper Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Unable to encrypt object[[B@8c9d9a1]
org.openbase.jul.exception.FatalImplementationErrorException: Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Unable to encrypt object[[B@8c9d9a1]
	at org.openbase.bco.authentication.lib.EncryptionHelper.encrypt(EncryptionHelper.java:194)
	at org.openbase.bco.authentication.lib.EncryptionHelper.encrypt(EncryptionHelper.java:157)
	at org.openbase.bco.authentication.lib.AuthenticationServerHandler.handleKDCRequest(AuthenticationServerHandler.java:96)
	at org.openbase.bco.authentication.core.AuthenticatorController.lambda$requestTicketGrantingTicket$0(AuthenticatorController.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.crypto.IllegalBlockSizeException: Data must not be longer than 117 bytes
	at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:347)
	at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at org.openbase.bco.authentication.lib.EncryptionHelper.encrypt(EncryptionHelper.java:190)
	... 7 common frames omitted
20:40:06.159 [pool-1-thread-46] ERROR o.o.b.a.l.EncryptionHelper =====================================
20:40:06.162 [pool-1-thread-46] ERROR o.o.b.a.c.AuthenticatorController ═╦═⚀ Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Unable to encrypt object[[B@8c9d9a1]
20:40:06.162 [pool-1-thread-46] ERROR o.o.b.a.c.AuthenticatorController  ╚════⚀ Data must not be longer than 117 bytes
20:40:06.162 [pool-1-thread-46] ERROR o.o.b.a.c.AuthenticatorController =====================================
20:40:06.162 [pool-1-thread-46] ERROR o.o.b.a.c.AuthenticatorController Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Unable to encrypt object[[B@8c9d9a1]
org.openbase.jul.exception.FatalImplementationErrorException: Fatal implementation error in or by using class org.openbase.bco.authentication.lib.EncryptionHelper: Unable to encrypt object[[B@8c9d9a1]
	at org.openbase.bco.authentication.lib.EncryptionHelper.encrypt(EncryptionHelper.java:194)
	at org.openbase.bco.authentication.lib.EncryptionHelper.encrypt(EncryptionHelper.java:157)
	at org.openbase.bco.authentication.lib.AuthenticationServerHandler.handleKDCRequest(AuthenticationServerHandler.java:96)
	at org.openbase.bco.authentication.core.AuthenticatorController.lambda$requestTicketGrantingTicket$0(AuthenticatorController.java:247)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.crypto.IllegalBlockSizeException: Data must not be longer than 117 bytes
	at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:347)
	at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:392)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at org.openbase.bco.authentication.lib.EncryptionHelper.encrypt(EncryptionHelper.java:190)
	... 7 common frames omitted
20:40:06.162 [pool-1-thread-46] ERROR o.o.b.a.c.AuthenticatorController =====================================
20:40:06.162 [pool-1-thread-35] ERROR o.o.b.a.c.AuthenticatorController ═╦═⚀ Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
20:40:06.162 [pool-1-thread-35] ERROR o.o.b.a.c.AuthenticatorController  ╚════⚀ Internal server error. Please try again.
20:40:06.162 [pool-1-thread-35] ERROR o.o.b.a.c.AuthenticatorController =====================================
20:40:06.162 [pool-1-thread-35] ERROR o.o.b.a.c.AuthenticatorController Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
	at org.openbase.jul.communication.controller.RPCHelper.lambda$registerMethod$1(RPCHelper.java:165)
	at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:121)
	at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:204)
	at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:174)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at org.openbase.jul.communication.controller.RPCHelper.lambda$registerMethod$1(RPCHelper.java:138)
	... 7 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	at org.openbase.bco.authentication.core.AuthenticatorController.lambda$requestTicketGrantingTicket$0(AuthenticatorController.java:254)
	... 4 common frames omitted
20:40:06.162 [pool-1-thread-35] ERROR o.o.b.a.c.AuthenticatorController =====================================
Jun 30, 2020 8:40:06 PM rsb.patterns.LocalMethod prepareErrorReply
WARNING: Exception during method invocation in participant: /bco/authentication/requestTicketGrantingTicket/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
20:40:06.181 [pool-1-thread-2] ERROR o.o.b.a.l.SessionManager ═╦═⚀ Remote task failed!
20:40:06.181 [pool-1-thread-2] ERROR o.o.b.a.l.SessionManager  ╚══╦═⚀ Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e! Details: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
20:40:06.181 [pool-1-thread-2] ERROR o.o.b.a.l.SessionManager     ╚════⚀ Internal server error. Please try again.
20:40:06.181 [pool-1-thread-2] ERROR o.o.b.a.l.SessionManager =====================================
20:40:06.182 [pool-1-thread-2] ERROR o.o.b.a.l.SessionManager Remote task failed!
org.openbase.jul.extension.rsb.com.exception.RSBResolvedException: Remote task failed!
	at org.openbase.jul.extension.rsb.com.RSBFutureImpl.get(RSBFutureImpl.java:78)
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:375)
	at org.openbase.bco.authentication.lib.SessionManager.loginUser(SessionManager.java:262)
	at org.openbase.bco.authentication.lib.SessionManager.loginUser(SessionManager.java:232)
	at org.openbase.bco.device.openhab.registry.OpenHABConfigSynchronizer.activate(OpenHABConfigSynchronizer.java:75)
	at org.openbase.jul.pattern.launch.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:191)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e! Details: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openbase.jul.extension.rsb.com.exception.RSBResolvedException.resolveRSBException(RSBResolvedException.java:108)
	at org.openbase.jul.extension.rsb.com.exception.RSBResolvedException.<init>(RSBResolvedException.java:51)
	... 10 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	... 16 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	... 16 common frames omitted
20:40:06.182 [pool-1-thread-2] ERROR o.o.b.a.l.SessionManager =====================================
20:40:06.182 [pool-1-thread-2] INFO  o.o.b.a.l.SessionManager Login failed: 
org.openbase.jul.exception.CouldNotPerformException: Internal server error.
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:426)
	at org.openbase.bco.authentication.lib.SessionManager.loginUser(SessionManager.java:262)
	at org.openbase.bco.authentication.lib.SessionManager.loginUser(SessionManager.java:232)
	at org.openbase.bco.device.openhab.registry.OpenHABConfigSynchronizer.activate(OpenHABConfigSynchronizer.java:75)
	at org.openbase.jul.pattern.launch.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:191)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openbase.jul.extension.rsb.com.exception.RSBResolvedException: Remote task failed!
	at org.openbase.jul.extension.rsb.com.RSBFutureImpl.get(RSBFutureImpl.java:78)
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:375)
	... 8 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e! Details: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openbase.jul.extension.rsb.com.exception.RSBResolvedException.resolveRSBException(RSBResolvedException.java:108)
	at org.openbase.jul.extension.rsb.com.exception.RSBResolvedException.<init>(RSBResolvedException.java:51)
	... 10 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	... 16 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	... 16 common frames omitted
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher ═╦═⚀ could not launch OpenHABConfigSynchronizerLauncher
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher  ╚══╦═⚀ Internal server error.
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher     ╚══╦═⚀ Remote task failed!
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher        ╚══╦═⚀ Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e! Details: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher           ╚════⚀ Internal server error. Please try again.
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher =====================================
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher could not launch OpenHABConfigSynchronizerLauncher
org.openbase.jul.exception.CouldNotPerformException: could not launch OpenHABConfigSynchronizerLauncher
	at org.openbase.jul.pattern.launch.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:208)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Internal server error.
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:426)
	at org.openbase.bco.authentication.lib.SessionManager.loginUser(SessionManager.java:262)
	at org.openbase.bco.authentication.lib.SessionManager.loginUser(SessionManager.java:232)
	at org.openbase.bco.device.openhab.registry.OpenHABConfigSynchronizer.activate(OpenHABConfigSynchronizer.java:75)
	at org.openbase.jul.pattern.launch.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:191)
	... 4 common frames omitted
Caused by: org.openbase.jul.extension.rsb.com.exception.RSBResolvedException: Remote task failed!
	at org.openbase.jul.extension.rsb.com.RSBFutureImpl.get(RSBFutureImpl.java:78)
	at org.openbase.bco.authentication.lib.SessionManager.internalLogin(SessionManager.java:375)
	... 8 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e! Details: Could not invoke Method[Class requestTicketGrantingTicket(UserClientPair)] of org.openbase.bco.authentication.core.AuthenticatorController@7ef4eb4e!
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openbase.jul.extension.rsb.com.exception.RSBResolvedException.resolveRSBException(RSBResolvedException.java:108)
	at org.openbase.jul.extension.rsb.com.exception.RSBResolvedException.<init>(RSBResolvedException.java:51)
	... 10 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	... 16 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Internal server error. Please try again.
	... 16 common frames omitted
20:40:06.183 [pool-1-thread-2] ERROR o.o.b.d.o.r.OpenHABConfigSynchronizerLauncher =====================================
</pre>

**Comment by pLeminoq** [comment]
I did some investigation and now know what the issue is, but I don't know a solution yet.
The problem occurs because the OpenHABConfigSynchronizer tries to login the OpenHAB User.
Because the OpenHAB device manager is now started in the same JVM as the other components, the BCO user is already logged in.
This sounds like normal behavior but this is the first time the client as well as the user use asymmetric encryption.
If a client and a user try to log in, the ticket granting key is encrypted with both of their keys.
This is a problem if both are logged in with asymmetric encryption because this results in an encrypted object which is too large after the first encryption.
Note: in asymmetric encryption there is a limit of the size of the object to encrypt based on the size of the key (https://stackoverflow.com/questions/10007147/getting-a-illegalblocksizeexception-data-must-not-be-longer-than-256-bytes-when).
This sounds like we should just increase the asymmetric keys, but the result of an asymmetric encryption depends on the key size as well.
So this does not work either.

I created a unit test on the branch issue-81 for this problem.
As long as we do not have a solution to it we have two options: either start the device manager separately or change the credentials of the OpenHAB User to be symmetric.

**Comment by DivineThreepwood** [comment]
Thanks for the feedback and issue description.
> change the credentials of the OpenHAB User to be symmetric.

Just to clarify some things, this would not fix the initial issue right? Even when allowing the bco user to be logged in as client and the openhab user logged in as user this would fix the initial issues such as: 
* In case the bco core components are submitting any actions, those would be executed in the name of the openhab user, right?
* as soon as more than two device-managers are started within the same process we got a problem since only one device manager user can be logged in at a time.

If I am correct, the openhab user was initially introduced because of two aspects.
1. To authenticate any externally started bco module
    * For this I would like to have pub sup authentication (#49 already supported on device level, right?) where the public keys of additional bco nodes can be registered on the core node. This would remove the need of the openhab user on this level.
2. To authorise any action performed by the device manager such as a user control a physical button which then triggers a scene. In this case the action is currently performed by the openhab user which is marked as human by default. However, this was never a nice design anyway.
  * Would it not be possible to authorise the device manager actions by using user tokens registered at action parameter level? Therefore, the action authorisation is independent of 
the user currently logged in at the main session manager and additionally this would avoid the duplicated asymmetric encryption, right?

What do you thing about this solution and could you implement a check that throws a NotSupportedException when both user and client are trying to login in an asynchronously way?

**Comment by pLeminoq** [comment]
> Just to clarify some things, this would not fix the initial issue right?

No, this would not fix the initial issue and yes it would have the consequences you stated.

> For this I would like to have pub sup authentication (#49 already supported on device level, right?) where the public keys of additional bco nodes can be registered on the core node. This would remove the need of the openhab user on this level.

I don't really know what you mean by "pub sup authentication". #49 is only about logging in users with private-public-keys which is already implements - so it can be closed.

> Would it not be possible to authorise the device manager actions by using user tokens registered at action parameter level? Therefore, the action authorisation is independent of
the user currently logged in at the main session manager and additionally this would avoid the duplicated asymmetric encryption, right?

I think this would be a good solution. The only thing I can thinks of is that this may be a security problem if you use the OpenHAB user to limit its permissions so that OpenHAB cannot see certain devices. The reason being that if the token is left out for any request (e.g. to the registry) the BCO user's permissions are used which generally means that all devices are visible.

**Comment by pLeminoq** [comment]
> could you implement a check that throws a NotSupportedException when both user and client are trying to login in an asynchronously way?

Implemented and created a pull request (https://github.com/openbase/bco.authentication/pull/82) so that you can have a look at it.
